import React, { createContext, useContext, useEffect, useState } from 'react';

const GlobalSettingsContext = createContext({
  theme: 'light',
  toggleTheme: () => {},
  language: 'en',
  setLanguage: () => {},
  t: () => {},
});

export const GlobalSettingsProvider = ({ children }) => {
  const [theme, setTheme] = useState(() => localStorage.getItem('bashcare_theme') || 'light');
  const [language, setLanguage] = useState(() => localStorage.getItem('bashcare_lang') || 'en');

  const translations = {
    en: {
      home: 'Home',
      services: 'Services',
      about: 'About',
      contact: 'Contact',
      help: 'Help',
      dashboard: 'Dashboard',
      appointments: 'Appointments',
      doctors: 'Doctors',
      messages: 'Messages',
      records: 'Medical Records',
      prescriptions: 'Prescriptions',
      notifications: 'Notifications',
      settings: 'Settings',
      logout: 'Logout',
      welcome: 'Welcome',
      search: 'Search',
      patients: 'My Patients',
      queue: 'Patient Queue',
      consultations: 'Consultations',
      schedule: 'Schedule',
      verifications: 'Verification Monitor',
      staff: 'Staff Management',
      departments: 'Departments',
      finance: 'Billing & Finance',
      logs: 'System Logs',
      audit: 'Audit Reports',
      directory: 'Verified Directory',
      pending: 'Pending Verifications',
      overview: 'Overview',
      profile: 'Profile',
      users: 'User Management',
      monitoring: 'Request Monitoring',
      vitals: 'Health Tracker',
      symptomGuide: 'Symptom Guide',
    },
    fr: {
      home: 'Accueil',
      services: 'Services',
      about: 'À propos',
      contact: 'Contact',
      help: 'Aide',
      dashboard: 'Tableau de bord',
      appointments: 'Rendez-vous',
      doctors: 'Médecins',
      messages: 'Messages',
      records: 'Dossiers médicaux',
      prescriptions: 'Ordonnances',
      notifications: 'Notifications',
      settings: 'Paramètres',
      logout: 'Déconnexion',
      welcome: 'Bienvenue',
      search: 'Recherche',
      patients: 'Mes patients',
      queue: 'File d\'attente',
      consultations: 'Consultations',
      schedule: 'Emploi du temps',
      verifications: 'Moniteur de vérification',
      staff: 'Gestion du personnel',
      departments: 'Départements',
      finance: 'Facturation et finance',
      logs: 'Journaux système',
      audit: 'Rapports d\'audit',
      directory: 'Répertoire vérifié',
      pending: 'Vérifications en attente',
      overview: 'Aperçu',
      profile: 'Profil',
      users: 'Gestion des utilisateurs',
      monitoring: 'Suivi des demandes',
      vitals: 'Suivi de Santé',
      symptomGuide: 'Guide des Symptômes',
      
      // Hero Section
      'Now Accepting Online Consultations': 'Accepte maintenant les consultations en ligne',
      'Compassionate Care': 'Soins Compatissants',
      'for a Better Life': 'pour une Vie Meilleure',
      'Bashcare Hub provides top-tier medical services with a team of experienced professionals. We are committed to your health and well-being.': 'Bashcare Hub fournit des services médicaux de premier ordre avec une équipe de professionnels expérimentés. Nous nous engageons pour votre santé et votre bien-être.',
      'Search specialties, doctors, or symptoms...': 'Rechercher des spécialités, des médecins ou des symptômes...',
      'Explore Services': 'Explorer les Services',
      'Our Specialists': 'Nos Spécialistes',
      'Active Doctors': 'Médecins actifs',
      'Satisfaction Rate': 'Taux de satisfaction',
      'Verified Staff': 'Personnel vérifié',
      'Top Rated Care': 'Soins les mieux notés',
      '98 Doctors Online': '98 médecins en ligne',
      'AI Diagnostic Assistant Live': 'Assistant diagnostic IA en direct',
      'Department': 'Département',
      'Doctor': 'Médecin',
      'Date': 'Date',
      'Book Now': 'Réserver',
      'All': 'Tous',
      'All Doctors': 'Tous les médecins',

      // HighlightStrip
      'Expert Doctors': 'Médecins experts',
      '24/7 Support': 'Support 24/7',
      'Health Tracking': 'Suivi de santé',
      'Secure Records': 'Dossiers sécurisés',
      'Fast Appointments': 'Rendez-vous rapides',
      'Personal Care': 'Soins personnels',
      'Top Rated': 'Le mieux noté',
      'Online Pharmacy': 'Pharmacie en ligne',
      'Lab Results': 'Résultats de laboratoire',
      'Mental Health': 'Santé mentale',
      'Nutrition Plans': 'Plans de nutrition',
      'Telehealth': 'Télésanté',
      'Specialist Access': 'Accès aux spécialistes',
      'Family Plans': 'Plans familiaux',
      'Emergency Care': 'Soins d\'urgence',
      'Dental Services': 'Services dentaires',
      'Gynecology': 'Gynécologie',
      'Diagnostics': 'Diagnostics',
      'Vaccination': 'Vaccination',
      'Cancer Screening': 'Dépistage du cancer',
      'Eye Care': 'Soins des yeux',
      'Physical Therapy': 'Physiothérapie',
      'Surgery': 'Chirurgie',
      'Radiology': 'Radiologie',
      'Pharmacy': 'Pharmacie',
      'AI Diagnostics': 'Diagnostics IA',
      'Home Visits': 'Visites à domicile',
      'Second Opinion': 'Second avis',
      'Wellness Check': 'Bilan de santé',

      // Features
      'Our Departments': 'Nos Départements',
      'Specialized care across every discipline — find the right department for your needs.': 'Soins spécialisés dans chaque discipline — trouvez le bon département pour vos besoins.',
      'Pediatric Dept': 'Dépt pédiatrique',
      'General Medicine': 'Médecine générale',
      'Our Premium Healthcare Experience': 'Notre Expérience de Santé Premium',
      'Everything you need for a healthier life, delivered with precision and compassion.': 'Tout ce dont vous avez besoin pour une vie plus saine, fourni avec précision et compassion.',
      'World-Class Medical Expertise': 'Expertise Médicale de Classe Mondiale',
      'Our network of doctors comprises some of the finest minds in medicine. From board-certified surgeons to compassionate general practitioners, we ensure you have access to the highest level of care. We continuously invest in training and research to stay at the forefront of medical science.': 'Notre réseau de médecins comprend certains des meilleurs esprits de la médecine. Des chirurgiens certifiés aux médecins généralistes compatissants, nous vous garantissons l\'accès au plus haut niveau de soins. Nous investissons continuellement dans la formation et la recherche pour rester à la pointe de la science médicale.',
      '24/7 Emergency & Support': 'Urgence et Support 24/7',
      'Health emergencies don\'t follow a schedule, and neither do we. Our dedicated support team and emergency services are available around the clock, ensuring that help is always just a phone call or a click away, no matter the time or place.': 'Les urgences médicales ne suivent pas d\'horaire, et nous non plus. Notre équipe de soutien dédiée et nos services d\'urgence sont disponibles 24 heures sur 24, garantissant que l\'aide est toujours à portée de main ou de clic, peu importe l\'heure ou le lieu.',
      'Cutting-Edge Medical Tech': 'Technologie Médicale de Pointe',
      'We integrate the latest AI-driven diagnostics and telemedicine tools to provide faster, more accurate results. Our facilities are equipped with next-generation machinery that reduces recovery time and increases precision in every procedure.': 'Nous intégrons les derniers outils de télémédecine et de diagnostic pilotés par l\'IA pour fournir des résultats plus rapides et plus précis. Nos installations sont équipées de machines de nouvelle génération qui réduisent le temps de récupération et augmentent la précision de chaque procédure.',
      'Comprehensive Wellness Plans': 'Plans de Bien-être Complets',
      'Healthcare is more than just treating illness; it\'s about maintaining wellness. We offer holistic health packages including nutrition guidance, mental health support, and preventative screenings to keep you in peak condition.': 'La santé est plus que le simple traitement des maladies ; il s\'agit de maintenir le bien-être. Nous offrons des forfaits de santé holistiques comprenant des conseils en nutrition, un soutien en santé mentale et des dépistages préventifs pour vous maintenir en pleine forme.',
      'Learn More': 'En savoir plus',

      // WhyChooseUs
      'Why Choose Bashcare Hub?': 'Pourquoi choisir Bashcare Hub ?',
      'We combine medical excellence with technological innovation to provide a healthcare experience that is truly modern and compassionate.': 'Nous combinons l\'excellence médicale avec l\'innovation technologique pour offrir une expérience de soins de santé véritablement moderne et compatissante.',
      'Patient-Centric Approach': 'Approche centrée sur le patient',
      'We believe in treating the person, not just the symptoms. Our personalized care plans are tailored to your unique health history and goals.': 'Nous croyons au traitement de la personne, pas seulement des symptômes. Nos plans de soins personnalisés sont adaptés à vos antécédents de santé et à vos objectifs uniques.',
      'World-Class Specialists': 'Spécialistes de classe mondiale',
      'Our network consists of board-certified doctors and specialists who bring years of experience from leading medical institutions worldwide.': 'Notre réseau est composé de médecins et de spécialistes certifiés qui apportent des années d\'expérience de grandes institutions médicales du monde entier.',
      'Advanced Diagnostics': 'Diagnostics avancés',
      'Equipped with the latest AI-driven diagnostic tools, we ensure accurate and early detection of health issues for better outcomes.': 'Équipés des derniers outils de diagnostic pilotés par l\'IA, nous assurons une détection précoce et précise des problèmes de santé pour de meilleurs résultats.',
      'Seamless Digital Experience': 'Expérience numérique transparente',
      'From booking appointments to receiving digital prescriptions, our platform makes managing your health as simple as a few clicks.': 'De la prise de rendez-vous à la réception d\'ordonnances numériques, notre plateforme simplifie la gestion de votre santé en quelques clics.',

      // ServicesGrid
      'Our Services': 'Nos Services',
      'Comprehensive medical care tailored to your needs. Find the right service for you.': 'Des soins médicaux complets adaptés à vos besoins. Trouvez le service qui vous convient.',
      'Online Consultations': 'Consultations en Ligne',
      'Consult with our certified specialists from the comfort of your home.': 'Consultez nos spécialistes certifiés depuis le confort de votre maison.',
      'Book Appointment': 'Prendre Rendez-vous',
      'Book appointments with top doctors in your area.': 'Prenez rendez-vous avec les meilleurs médecins de votre région.',
      'Secure Medical Records': 'Dossiers Médicaux Sécurisés',
      'Access and manage your medical records securely anytime, anywhere.': 'Accédez à vos dossiers médicaux et gérez-les en toute sécurité, n\'importe quand et n\'importe où.',
      'Verified Doctors': 'Médecins Vérifiés',
      'Search through our list of verified and certified medical professionals.': 'Recherchez dans notre liste de professionnels de santé vérifiés et certifiés.',
      'Emergency Support': 'Support d\'Urgence',
      'Get 24/7 medical assistance and emergency services.': 'Obtenez une assistance médicale 24/7 et des services d\'urgence.',
      'AI Symptom Checker': 'Vérificateur de Symptômes IA',
      'Check your symptoms using our advanced AI health assistant.': 'Vérifiez vos symptômes en utilisant notre assistant de santé IA avancé.',

      // MembershipPlans
      'Membership Plans': 'Plans d\'Adhésion',
      'Choose the plan that fits your lifestyle and healthcare needs.': 'Choisissez le plan qui correspond à votre style de vie et à vos besoins de santé.',
      'Free': 'Gratuit',
      'Basic healthcare management for individuals.': 'Gestion de base de la santé pour les particuliers.',
      'Standard': 'Standard',
      'Comprehensive care with priority support.': 'Soins complets avec assistance prioritaire.',
      'Premium': 'Premium',
      'Elite care with dedicated personal doctor.': 'Soins d\'élite avec médecin personnel dédié.',

      // FAQ
      'Frequently Asked Questions': 'Questions Fréquemment Posées',
      'Find answers to common questions about our services, verification, and plans.': 'Trouvez des réponses aux questions courantes sur nos services, notre vérification et nos forfaits.',
      'How do I book an appointment?': 'Comment puis-je prendre rendez-vous ?',
      'You can book an appointment by logging into your patient dashboard, selecting a doctor, and choosing a suitable date and time.': 'Vous pouvez prendre rendez-vous en vous connectant à votre tableau de bord patient, en sélectionnant un médecin et en choisissant une date et une heure appropriées.',
      'Are the doctors on Bashcare Hub verified?': 'Les médecins sur Bashcare Hub sont-ils vérifiés ?',
      'Yes, all medical professionals on our platform go through a rigorous verification process, including credentials, licenses, and background checks by our verification officers.': 'Oui, tous les professionnels de santé sur notre plateforme passent par un processus de vérification rigoureux, y compris les diplômes, les licences et les vérifications d\'antécédents par nos agents de vérification.',
      'Is my medical data secure?': 'Mes données médicales sont-elles sécurisées ?',
      'Absolutely. We use industry-standard encryption protocols and comply with data privacy regulations to ensure your medical records remain private and secure.': 'Absolument. Nous utilisons des protocoles de chiffrement conformes aux normes de l\'industrie et respectons les réglementations sur la confidentialité des données pour garantir la sécurité et la confidentialité de vos dossiers médicaux.',

      // CTA
      'Ready to Prioritize Your Health?': 'Prêt à Prioriser Votre Santé ?',
      'Join thousands of patients who trust Bashcare Hub for their healthcare journey. Sign up today and get started.': 'Rejoignez des milliers de patients qui font confiance à Bashcare Hub pour leur parcours de santé. Inscrivez-vous aujourd\'hui et commencez.',
      'Create Account': 'Créer un Compte',

      // Footer
      'Providing compassionate, high-quality healthcare at your fingertips. Your well-being is our ultimate mission.': 'Fournir des soins de santé compatissants et de haute qualité à portée de main. Votre bien-être est notre mission ultime.',
      'Platform': 'Plateforme',
      'Company': 'Entreprise',
      'Legal': 'Légal',
      'Privacy Policy': 'Politique de confidentialité',
      'Terms of Service': 'Conditions d\'utilisation',
      'Cookie Settings': 'Paramètres des cookies',
      'All rights reserved.': 'Tous droits réservés.',

      // About Page
      'About Us': 'À Propos de Nous',
      'Our Mission': 'Notre Mission',
      'Our Core Values': 'Nos Valeurs Fondamentales',
      'The principles that guide our every action.': 'Les principes qui guident chacune de nos actions.',
      'Patient-Centered': 'Centré sur le Patient',
      'Excellence': 'Excellence',
      'Innovation': 'Innovation',
      'Integrity': 'Intégrité',
      'Years of Experience': 'Années d\'Expérience',
      'Medical Team': 'Équipe Médicale',

      // Contact Page
      'Contact Us': 'Contactez-nous',
      'Get in touch with our team for any inquiries or support.': 'Prenez contact avec notre équipe pour toute demande ou assistance.',
      'Send us a message': 'Envoyez-nous un message',
      'First Name': 'Prénom',
      'Last Name': 'Nom de famille',
      'Email Address': 'Adresse e-mail',
      'Subject': 'Sujet',
      'Message': 'Message',
      'Send Message': 'Envoyer le Message',
      'Contact Information': 'Informations de Contact',
      'A patient-first support experience': 'Une expérience de support centrée sur le patient',
      'Need quick support?': 'Besoin d\'aide rapide ?',
      'Whether you need help booking appointments, managing records, or verifying doctor credentials, our support team is ready to respond fast.': 'Que vous ayez besoin d\'aide pour prendre rendez-vous, gérer vos dossiers ou vérifier les qualifications des médecins, notre équipe de soutien est prête à répondre rapidement.',

      // ServicesGrid
      'Our Specialized Services': 'Nos Services Spécialisés',
      'Experience modern, personalized medical care tailored to your needs.': 'Découvrez des soins médicaux modernes et personnalisés, adaptés à vos besoins.',
      'General': 'Général',
      'All': 'Tout',
      'Heart Checkup': 'Bilan Cardiaque',
      'Brain Mapping': 'Cartographie Cérébrale',
      'Child Vaccination': 'Vaccination Infantile',
      'ECG Analysis': 'Analyse ECG',
      'Bone Density Test': 'Ostéodensitométrie',
      'Full Body Scan': 'Scanner Corporel Complet',
      'Teeth Whitening': 'Blanchiment Dentaire',
      'Sleep Study': 'Étude du Sommeil',
      'Comprehensive cardiac evaluation and diagnostic testing.': 'Évaluation cardiaque complète et tests diagnostiques.',
      'Advanced neurological assessment using latest technology.': 'Évaluation neurologique avancée utilisant les dernières technologies.',
      'Safe and gentle vaccination services for your little ones.': 'Services de vaccination sûrs et doux pour vos tout-petits.',
      'Quick and accurate electrocardiogram readings.': 'Lectures d\'électrocardiogramme rapides et précises.',
      'Screening for osteoporosis and bone health.': 'Dépistage de l\'ostéoporose et de la santé osseuse.',
      'Complete health screening covering all vital organs.': 'Bilan de santé complet couvrant tous les organes vitaux.',
      'Professional dental cleaning and whitening services.': 'Services professionnels de nettoyage et de blanchiment des dents.',
      'Overnight monitoring for sleep disorders and apnea.': 'Surveillance nocturne des troubles du sommeil et de l\'apnée.',

      // MembershipPlans
      'Tailored Care Plans': 'Plans de Soins Sur Mesure',
      'Choose a plan that fits your lifestyle and health needs. From basic monitoring to elite family protection.': 'Choisissez un plan qui correspond à votre style de vie et à vos besoins de santé. Du suivi de base à la protection familiale d\'élite.',
      'Most Popular': 'Le Plus Populaire',
      'Basic Care': 'Soins de Base',
      'Premium Wellness': 'Bien-être Premium',
      'Elite Family': 'Famille Élite',
      'Essential health monitoring for everyone.': 'Suivi de santé essentiel pour tous.',
      'Comprehensive care for health-conscious individuals.': 'Soins complets pour les personnes soucieuses de leur santé.',
      'The ultimate healthcare protection for your whole family.': 'La protection de santé ultime pour toute votre famille.',
      'Monthly Health Report': 'Rapport de Santé Mensuel',
      'General Practitioner Chat': 'Chat avec un Généraliste',
      'Standard Appointment Booking': 'Réservation de Rendez-vous Standard',
      'Basic Medical Records': 'Dossiers Médicaux de Base',
      'Priority Appointment Booking': 'Réservation de Rendez-vous Prioritaire',
      'Specialist Consultations': 'Consultations Spécialisées',
      'Detailed Wellness Analytics': 'Analyses de Bien-être Détaillées',
      'Annual Full Body Scan': 'Scanner Corporel Annuel',
      '24/7 Emergency Access': 'Accès d\'Urgence 24/7',
      'Unlimited Family Members': 'Membres de la Famille Illimités',
      'Dedicated Family Physician': 'Médecin de Famille Dédié',
      'Home Visit Services': 'Services de Visites à Domicile',
      'VIP Clinic Access': 'Accès VIP en Clinique',
      'Full Genomic Screening': 'Dépistage Génomique Complet',
      'Go Premium': 'Devenir Premium',
      'Join Elite': 'Rejoindre l\'Élite',

      // FAQ
      'Quick answers to common questions about our world-class services.': 'Réponses rapides aux questions courantes sur nos services de classe mondiale.',
      'How can I book an appointment?': 'Comment puis-je prendre rendez-vous ?',
      'You can book an appointment through our online booking system via the \'Get Started\' button, or by calling our 24/7 helpline at +1 (555) 123-4567. We offer both virtual and in-person consultations.': 'Vous pouvez prendre rendez-vous via notre système de réservation en ligne avec le bouton « Commencer », ou en appelant notre ligne d\'assistance 24/7 au +1 (555) 123-4567. Nous proposons des consultations virtuelles et en personne.',
      'Do you accept insurance?': 'Acceptez-vous les assurances ?',
      'Yes, we accept most major health insurance providers. Please bring your insurance card during your first visit or upload a copy during the online registration process for faster verification.': 'Oui, nous acceptons la plupart des grands assureurs de santé. Veuillez apporter votre carte d\'assurance lors de votre première visite ou en télécharger une copie lors de l\'inscription en ligne pour une vérification plus rapide.',
      'What should I bring for my first visit?': 'Que dois-je apporter pour ma première visite ?',
      'Please bring a valid government-issued ID, your insurance card, and any previous medical records, test results, or current prescriptions you are taking to ensure a comprehensive evaluation.': 'Veuillez apporter une pièce d\'identité valide délivrée par le gouvernement, votre carte d\'assurance et tout dossier médical antérieur, résultat de test ou ordonnance en cours pour garantir une évaluation complète.',
      'Is emergency care available?': 'Les soins d\'urgence sont-ils disponibles ?',
      'Absolutely. Our emergency department is open 24/7 with specialized trauma teams and advanced life-support equipment ready to assist you at any time.': 'Absolument. Notre service d\'urgences est ouvert 24h/24 et 7j/7 avec des équipes spécialisées en traumatologie et des équipements de réanimation avancés prêts à vous aider à tout moment.',
      'Can I consult with a doctor online?': 'Puis-je consulter un médecin en ligne ?',
      'Yes, we provide a fully integrated telemedicine platform. You can have a high-definition video call with our specialists from anywhere in the world.': 'Oui, nous fournissons une plateforme de télémédecine entièrement intégrée. Vous pouvez passer un appel vidéo haute définition avec nos spécialistes depuis n\'importe où dans le monde.',

      // CTA
      'Your Journey to Better Health Starts Here': 'Votre parcours vers une meilleure santé commence ici',
      'Experience world-class healthcare tailored to your needs. Join Bashcare Hub today and get access to top specialists and seamless digital care.': 'Faites l\'expérience de soins de santé de classe mondiale adaptés à vos besoins. Rejoignez Bashcare Hub aujourd\'hui et accédez aux meilleurs spécialistes et à des soins numériques fluides.',
      'Consult a Specialist': 'Consulter un spécialiste',

      // Footer
      'Providing excellence in medical care since 2024. We are committed to delivering the highest quality healthcare services to our community.': 'Fournir l\'excellence en matière de soins médicaux depuis 2024. Nous nous engageons à fournir des services de santé de la plus haute qualité à notre communauté.',
      'Quick Links': 'Liens rapides',
      'Specialties': 'Spécialités',
      'Help & FAQ': 'Aide et FAQ',
      'Get Started': 'Commencer',

      // About page additional
      'Leading the way in modern healthcare and patient management.': 'Ouvrir la voie à des soins de santé et à une gestion des patients modernes.',
      'Bashcare Hub was founded with a single goal: to make high-quality healthcare accessible, efficient, and compassionate. We bridge the gap between patients and providers through advanced technology and a dedicated network of medical professionals.': 'Bashcare Hub a été fondé avec un seul objectif : rendre les soins de santé de haute qualité accessibles, efficaces et compatissants. Nous comblons le fossé entre les patients et les prestataires grâce à une technologie de pointe et un réseau dédié de professionnels de la santé.',
      'Our platform integrates everything from appointment booking and record management to doctor verification and hospital administration, ensuring a seamless experience for everyone in the healthcare ecosystem.': 'Notre plateforme intègre tout, de la prise de rendez-vous et de la gestion des dossiers à la vérification des médecins et à l\'administration hospitalière, garantissant une expérience fluide pour tous les acteurs de l\'écosystème de santé.',
      'Everything we do is focused on providing the best possible care for our patients.': 'Tout ce que nous faisons est axé sur la fourniture des meilleurs soins possibles à nos patients.',
      'We strive for excellence in all our medical services and operational processes.': 'Nous visons l\'excellence dans tous nos services médicaux et processus opérationnels.',
      'Leveraging the latest technology to improve healthcare accessibility and outcomes.': 'Exploiter les dernières technologies pour améliorer l\'accessibilité et les résultats des soins de santé.',
      'We maintain the highest standards of professional and ethical conduct.': 'Nous maintenons les normes les plus élevées de conduite professionnelle et éthique.',
      'A connected care experience for everyone': 'Une expérience de soins connectée pour tous',
      'From telehealth follow-ups to secure record sharing, Bashcare Hub brings patients, specialists, and hospitals together in one intelligent platform.': 'Des suivis de télésanté au partage sécurisé des dossiers, Bashcare Hub rassemble les patients, les spécialistes et les hôpitaux au sein d\'une plateforme intelligente unique.',
      'Virtual consultations': 'Consultations virtuelles',
      'Book trusted specialists and talk to doctors online within minutes.': 'Réservez des spécialistes de confiance et parlez à des médecins en ligne en quelques minutes.',
      'AI-driven reminders': 'Rappels basés sur l\'IA',
      'Stay on top of care with intelligent health nudges and medication prompts.': 'Restez au fait des soins grâce à des alertes de santé intelligentes et des rappels de médicaments.',
      'Care coordination': 'Coordination des soins',
      'Link family, providers, and clinics for smoother treatment journeys.': 'Liez la famille, les prestataires et les cliniques pour des parcours de traitement plus fluides.',
      'Patients Served': 'Patients servis',
      'Hospital Partners': 'Hôpitaux partenaires',
      'Support Available': 'Support disponible',

      // Contact page additional
      'Our Office': 'Notre bureau',
      'Phone Number': 'Numéro de téléphone',
      'Working Hours': 'Heures de travail',
      'Have questions about our platform or services? Reach out to us through any of the following channels. Our team is always ready to help.': 'Vous avez des questions sur notre plateforme ou nos services ? Contactez-nous par l\'un des canaux suivants. Notre équipe est toujours prête à vous aider.',
      'General Inquiry': 'Demande générale',
      'Technical Support': 'Support technique',
      'Medical Partnership': 'Partenariat médical',
      'Billing Question': 'Question de facturation',
      'Fast Response': 'Réponse rapide',
      'We answer support requests quickly so you can keep your health plans moving.': 'Nous répondons rapidement aux demandes de support afin que vous puissiez continuer vos plans de santé.',
      'Verified Assistance': 'Assistance vérifiée',
      'Our team is trained to handle medical coordination and patient portal issues.': 'Notre équipe est formée pour gérer la coordination médicale et les problèmes de portail patient.',
      'Secure Follow-Up': 'Suivi sécurisé',
      'All communication is handled with privacy and HIPAA-style care in mind.': 'Toutes les communications sont traitées en gardant à l\'esprit la confidentialité et des soins de style HIPAA.',

      // Help page additional
      'Help & Support': 'Aide & Support',
      'Find answers to your questions or get in touch with our team.': 'Trouvez des réponses à vos questions ou contactez notre équipe.',
      'You can book an appointment by signing in as a Patient and navigating to the "Book Appointment" section. Choose your specialty, doctor, and preferred time slot.': 'Vous pouvez prendre rendez-vous en vous connectant en tant que patient et en naviguant vers la section « Prendre rendez-vous ». Choisissez votre spécialité, votre médecin et votre créneau horaire préféré.',
      'Yes, we use industry-standard encryption and follow strict privacy protocols to ensure your health records are only accessible to you and your authorized healthcare providers.': 'Oui, nous utilisons un cryptage conforme aux normes de l\'industrie et suivons des protocoles de confidentialité stricts pour garantir que vos dossiers de santé ne soient accessibles qu\'à vous et à vos professionnels de santé autorisés.',
      'How can I verify my doctor credentials?': 'Comment puis-je vérifier les qualifications de mon médecin ?',
      'All doctors on our platform go through a rigorous verification process by our dedicated Verification Officers before they can offer consultations.': 'Tous les médecins sur notre plateforme passent par un processus de vérification rigoureux par nos agents de vérification dédiés avant de pouvoir proposer des consultations.',
      'Can I manage multiple family members from one account?': 'Puis-je gérer plusieurs membres de ma famille à partir d\'un seul compte ?',
      'Currently, each account is for an individual. However, we are working on a "Family Plan" feature to allow managed care for dependents.': 'Actuellement, chaque compte est individuel. Cependant, nous travaillons sur une fonctionnalité de « Plan familial » pour permettre la gestion des soins pour les personnes dépendantes.',
      'What should I do in case of an emergency?': 'Que dois-je faire en cas d\'urgence ?',
      'Bashcare Hub is for non-emergency consultations. In case of a medical emergency, please call your local emergency services (e.g., 911) or go to the nearest hospital.': 'Bashcare Hub est destiné aux consultations non urgentes. En cas d\'urgence médicale, veuillez appeler vos services d\'urgence locaux (par exemple, le 15) ou vous rendre à l\'hôpital le plus proche.',
      'Need more help?': 'Besoin d\'aide supplémentaire ?',
      'Our support team is available 24/7 to assist you with any technical or medical inquiries.': 'Notre équipe de support est disponible 24h/24 et 7j/7 pour vous aider pour toute demande technique ou médicale.',
      'Live Chat': 'Chat en direct',
      'Average response: 2 mins': 'Réponse moyenne : 2 min',
      'Email Us': 'Envoyez-nous un e-mail',
      'Call Support': 'Appeler le support',
    },
    es: {
      home: 'Inicio',
      services: 'Servicios',
      about: 'Acerca de',
      contact: 'Contacto',
      help: 'Ayuda',
      dashboard: 'Panel de control',
      appointments: 'Citas',
      doctors: 'Médicos',
      messages: 'Mensajes',
      records: 'Registros médicos',
      prescriptions: 'Recetas',
      notifications: 'Notificaciones',
      settings: 'Ajustes',
      logout: 'Cerrar sesión',
      welcome: 'Bienvenido',
      search: 'Buscar',
      patients: 'Mis pacientes',
      queue: 'Cola de pacientes',
      consultations: 'Consultas',
      schedule: 'Horario',
      verifications: 'Monitor de verificación',
      staff: 'Gestión de personal',
      departments: 'Departamentos',
      finance: 'Facturación y finanzas',
      logs: 'Registros del sistema',
      audit: 'Informes de auditoría',
      directory: 'Directorio verificado',
      pending: 'Verificaciones pendientes',
      overview: 'Resumen',
      profile: 'Perfil',
      users: 'Gestión de usuarios',
      monitoring: 'Monitoreo de solicitudes',
      vitals: 'Seguimiento de Salud',
      symptomGuide: 'Guía de Síntomas',

      // Hero Section
      'Now Accepting Online Consultations': 'Ahora Aceptamos Consultas en Línea',
      'Compassionate Care': 'Cuidado Compasivo',
      'for a Better Life': 'para una Vida Mejor',
      'Bashcare Hub provides top-tier medical services with a team of experienced professionals. We are committed to your health and well-being.': 'Bashcare Hub ofrece servicios médicos de primer nivel con un equipo de profesionales experimentados. Estamos comprometidos con su salud y bienestar.',
      'Search specialties, doctors, or symptoms...': 'Buscar especialidades, médicos o síntomas...',
      'Explore Services': 'Explorar Servicios',
      'Our Specialists': 'Nuestros Especialistas',
      'Active Doctors': 'Médicos activos',
      'Satisfaction Rate': 'Tasa de satisfacción',
      'Verified Staff': 'Personal verificado',
      'Top Rated Care': 'Atención mejor valorada',
      '98 Doctors Online': '98 médicos en línea',
      'AI Diagnostic Assistant Live': 'Asistente de diagnóstico de IA en vivo',
      'Department': 'Departamento',
      'Doctor': 'Médico',
      'Date': 'Fecha',
      'Book Now': 'Reservar Ahora',
      'All': 'Todos',
      'All Doctors': 'Todos los médicos',

      // HighlightStrip
      'Expert Doctors': 'Médicos expertos',
      '24/7 Support': 'Soporte 24/7',
      'Health Tracking': 'Seguimiento de salud',
      'Secure Records': 'Registros seguros',
      'Fast Appointments': 'Citas rápidas',
      'Personal Care': 'Cuidado personal',
      'Top Rated': 'Mejor valorado',
      'Online Pharmacy': 'Farmacia en línea',
      'Lab Results': 'Resultados de laboratorio',
      'Mental Health': 'Salud mental',
      'Nutrition Plans': 'Planes de nutrición',
      'Telehealth': 'Telemedicina',
      'Specialist Access': 'Acceso a especialistas',
      'Family Plans': 'Planes familiares',
      'Emergency Care': 'Atención de emergencia',
      'Dental Services': 'Servicios dentares',
      'Gynecology': 'Ginecología',
      'Diagnostics': 'Diagnósticos',
      'Vaccination': 'Vacunación',
      'Cancer Screening': 'Detección de cáncer',
      'Eye Care': 'Cuidado ocular',
      'Physical Therapy': 'Fisioterapia',
      'Surgery': 'Cirugía',
      'Radiology': 'Radiología',
      'Pharmacy': 'Farmacia',
      'AI Diagnostics': 'Diagnósticos de IA',
      'Home Visits': 'Visitas domiciliarias',
      'Second Opinion': 'Segunda opinión',
      'Wellness Check': 'Chequeo de bienestar',

      // Features
      'Our Departments': 'Nuestros Departamentos',
      'Specialized care across every discipline — find the right department for your needs.': 'Atención especializada en cada disciplina — encuentre el departamento adecuado para sus necesidades.',
      'Pediatric Dept': 'Depto de pediatría',
      'General Medicine': 'Medicina general',
      'Our Premium Healthcare Experience': 'Nuestra Experiencia de Atención Médica Premium',
      'Everything you need for a healthier life, delivered with precision and compassion.': 'Todo lo que necesita para una vida más saludable, entregado con precisión y compasión.',
      'World-Class Medical Expertise': 'Experiencia Médica de Clase Mundial',
      'Our network of doctors comprises some of the finest minds in medicine. From board-certified surgeons to compassionate general practitioners, we ensure you have access to the highest level of care. We continuously invest in training and research to stay at the forefront of medical science.': 'Nuestra red de médicos incluye algunas de las mentes más brillantes de la medicina. Desde cirujanos certificados hasta médicos generales compasivos, nos aseguramos de que tenga acceso al más alto nivel de atención. Invertimos continuamente en capacitación e investigación para mantenernos a la vanguardia de la ciencia médica.',
      '24/7 Emergency & Support': 'Soporte y Emergencias 24/7',
      'Health emergencies don\'t follow a schedule, and neither do we. Our dedicated support team and emergency services are available around the clock, ensuring that help is always just a phone call or a click away, no matter the time or place.': 'Las urgencias médicas no siguen un horario, y nosotros tampoco. Nuestro dedicado equipo de soporte y servicios de emergencia están disponibles las 24 horas, asegurando que la ayuda esté siempre a una llamada o un clic de distancia, sin importar la hora o el lugar.',
      'Cutting-Edge Medical Tech': 'Tecnología Médica de Vanguardia',
      'We integrate the latest AI-driven diagnostics and telemedicine tools to provide faster, more accurate results. Our facilities are equipped with next-generation machinery that reduces recovery time and increases precision in every procedure.': 'Integramos las últimas herramientas de diagnóstico y telemedicina impulsadas por IA para proporcionar resultados más rápidos y precisos. Nuestras instalaciones están equipadas con maquinaria de última generación que reduce el tiempo de recuperación y aumenta la precisión en cada procedimiento.',
      'Comprehensive Wellness Plans': 'Planes Integrales de Bienestar',
      'Healthcare is more than just treating illness; it\'s about maintaining wellness. We offer holistic health packages including nutrition guidance, mental health support, and preventative screenings to keep you in peak condition.': 'La atención médica es más que solo tratar enfermedades; se trata de mantener el bienestar. Ofrecemos paquetes de salud holísticos que incluyen orientación nutricional, apoyo de salud mental y exámenes preventivos para mantenerlo en óptimas condiciones.',
      'Learn More': 'Más información',

      // WhyChooseUs
      'Why Choose Bashcare Hub?': '¿Por qué elegir Bashcare Hub?',
      'We combine medical excellence with technological innovation to provide a healthcare experience that is truly modern and compassionate.': 'Combinamos la excelencia médica con la innovación tecnológica para brindar una experiencia de atención médica verdaderamente moderna y compasiva.',
      'Patient-Centric Approach': 'Enfoque Centrado en el Paciente',
      'We believe in treating the person, not just the symptoms. Our personalized care plans are tailored to your unique health history and goals.': 'Creemos en tratar a la persona, no solo los síntomas. Nuestros planes de atención personalizados se adaptan a su historial de salud y objetivos únicos.',
      'World-Class Specialists': 'Especialistas de Clase Mundial',
      'Our network consists of board-certified doctors and specialists who bring years of experience from leading medical institutions worldwide.': 'Nuestra red consta de médicos y especialistas certificados que aportan años de experiencia de instituciones médicas líderes en todo el mundo.',
      'Advanced Diagnostics': 'Diagnósticos Avanzados',
      'Equipped with the latest AI-driven diagnostic tools, we ensure accurate and early detection of health issues for better outcomes.': 'Equipados con las últimas herramientas de diagnóstico impulsadas por IA, garantizamos una detección temprana y precisa de los problemas de salud para obtener mejores resultados.',
      'Seamless Digital Experience': 'Experiencia Digital Fluida',
      'From booking appointments to receiving digital prescriptions, our platform makes managing your health as simple as a few clicks.': 'Desde la reserva de citas hasta la recepción de recetas digitales, nuestra plataforma hace que la gestión de su salud sea tan sencilla como unos pocos clics.',

      // ServicesGrid
      'Our Services': 'Nuestros Servicios',
      'Comprehensive medical care tailored to your needs. Find the right service for you.': 'Atención médica integral adaptada a sus necesidades. Encuentre el servicio adecuado para usted.',
      'Online Consultations': 'Consultas en Línea',
      'Consult with our certified specialists from the comfort of your home.': 'Consulte con nuestros especialistas certificados desde la comodidad de su hogar.',
      'Book Appointment': 'Reservar Cita',
      'Book appointments with top doctors in your area.': 'Reserve citas con los mejores médicos de su área.',
      'Secure Medical Records': 'Registros Médicos Seguros',
      'Access and manage your medical records securely anytime, anywhere.': 'Acceda y administre sus registros médicos de manera segura en cualquier momento y lugar.',
      'Verified Doctors': 'Médicos Verificados',
      'Search through our list of verified and certified medical professionals.': 'Busque en nuestra lista de profesionales médicos verificados y certificados.',
      'Emergency Support': 'Soporte de Emergencia',
      'Get 24/7 medical assistance and emergency services.': 'Obtenga asistencia médica las 24 horas, los 7 días de la semana y servicios de emergencia.',
      'AI Symptom Checker': 'Verificador de Síntomas de IA',
      'Check your symptoms using our advanced AI health assistant.': 'Verifique sus síntomas usando nuestro asistente de salud de IA avanzado.',

      // MembershipPlans
      'Membership Plans': 'Planes de Membresía',
      'Choose the plan that fits your lifestyle and healthcare needs.': 'Elija el plan que se adapte a su estilo de vida y necesidades de atención médica.',
      'Free': 'Gratis',
      'Basic healthcare management for individuals.': 'Gestión básica de la salud para personas.',
      'Standard': 'Estándar',
      'Comprehensive care with priority support.': 'Atención integral con soporte prioritario.',
      'Premium': 'Premium',
      'Elite care with dedicated personal doctor.': 'Atención de élite con médico personal dedicado.',

      // FAQ
      'Frequently Asked Questions': 'Preguntas Frecuentes',
      'Find answers to common questions about our services, verification, and plans.': 'Encuentre respuestas a preguntas comunes sobre nuestros servicios, verificación y planes.',
      'How do I book an appointment?': '¿Cómo reservo una cita?',
      'You can book an appointment by logging into your patient dashboard, selecting a doctor, and choosing a suitable date and time.': 'Puede reservar una cita iniciando sesión en su panel de paciente, seleccionando un médico y eligiendo una fecha y hora adecuadas.',
      'Are the doctors on Bashcare Hub verified?': '¿Están verificados los médicos en Bashcare Hub?',
      'Yes, all medical professionals on our platform go through a rigorous verification process, including credentials, licenses, and background checks by our verification officers.': 'Sí, todos los profesionales médicos en nuestra plataforma pasan por un riguroso proceso de verificación, que incluye credenciales, licencias y verificaciones de antecedentes por parte de nuestros oficiales de verificación.',
      'Is my medical data secure?': '¿Son seguros mis datos médicos?',
      'Absolutely. We use industry-standard encryption protocols and comply with data privacy regulations to ensure your medical records remain private and secure.': 'Absolutamente. Utilizamos protocolos de cifrado estándar de la industria y cumplimos con las regulaciones de privacidad de datos para garantizar que sus registros médicos permanezcan privados y seguros.',

      // CTA
      'Ready to Prioritize Your Health?': '¿Listo para Priorizar su Salud?',
      'Join thousands of patients who trust Bashcare Hub for their healthcare journey. Sign up today and get started.': 'Únase a miles de pacientes que confían en Bashcare Hub para su viaje de atención médica. Regístrese hoy y comience.',
      'Create Account': 'Crear Cuenta',

      // Footer
      'Providing compassionate, high-quality healthcare at your fingertips. Your well-being is our ultimate mission.': 'Brindando atención médica compasiva y de alta calidad al alcance de su mano. Su bienestar es nuestra misión final.',
      'Platform': 'Plataforma',
      'Company': 'Compañía',
      'Legal': 'Legal',
      'Privacy Policy': 'Política de privacidad',
      'Terms of Service': 'Términos de servicio',
      'Cookie Settings': 'Configuración de cookies',
      'All rights reserved.': 'Todos los derechos reservados.',

      // About Page
      'About Us': 'Sobre Nosotros',
      'Our Mission': 'Nuestra Misión',
      'Our Core Values': 'Nuestros Valores Fundamentales',
      'The principles that guide our every action.': 'Los principios que guían cada una de nuestras acciones.',
      'Patient-Centered': 'Centrado en el Paciente',
      'Excellence': 'Excelencia',
      'Innovation': 'Innovación',
      'Integrity': 'Integridad',
      'Years of Experience': 'Años de Experiencia',
      'Medical Team': 'Equipo Médico',

      // Contact Page
      'Contact Us': 'Contáctenos',
      'Get in touch with our team for any inquiries or support.': 'Póngase en contacto con nuestro equipo para cualquier consulta o soporte.',
      'Send us a message': 'Envíenos un mensaje',
      'First Name': 'Nombre',
      'Last Name': 'Apellido',
      'Email Address': 'Dirección de correo electrónico',
      'Subject': 'Asunto',
      'Message': 'Mensaje',
      'Send Message': 'Enviar Mensaje',
      'Contact Information': 'Información de Contacto',
      'A patient-first support experience': 'Una experiencia de soporte centrada en el paciente',
      'Need quick support?': '¿Necesita soporte rápido?',
      'Whether you need help booking appointments, managing records, or verifying doctor credentials, our support team is ready to respond fast.': 'Ya sea que necesite ayuda para reservar citas, administrar registros o verificar las credenciales de los médicos, nuestro equipo de soporte está listo para responder rápidamente.',

      // ServicesGrid
      'Our Specialized Services': 'Nuestros Servicios Especializados',
      'Experience modern, personalized medical care tailored to your needs.': 'Experimente una atención médica moderna y personalizada adaptada a sus necesidades.',
      'General': 'General',
      'All': 'Todo',
      'Heart Checkup': 'Chequeo Cardíaco',
      'Brain Mapping': 'Mapeo Cerebral',
      'Child Vaccination': 'Vacunación Infantil',
      'ECG Analysis': 'Análisis de ECG',
      'Bone Density Test': 'Prueba de Densidad Ósea',
      'Full Body Scan': 'Escaneo Corporal Completo',
      'Teeth Whitening': 'Blanqueamiento Dental',
      'Sleep Study': 'Estudio del Sueño',
      'Comprehensive cardiac evaluation and diagnostic testing.': 'Evaluación cardíaca integral y pruebas de diagnóstico.',
      'Advanced neurological assessment using latest technology.': 'Evaluación neurológica avanzada utilizando la última tecnología.',
      'Safe and gentle vaccination services for your little ones.': 'Servicios de vacunación seguros y suaves para sus pequeños.',
      'Quick and accurate electrocardiogram readings.': 'Lecturas de electrocardiograma rápidas y precisas.',
      'Screening for osteoporosis and bone health.': 'Examen para la osteoporosis y la salud ósea.',
      'Complete health screening covering all vital organs.': 'Chequeo de salud completo que cubre todos los órganos vitales.',
      'Professional dental cleaning and whitening services.': 'Servicios profesionales de limpieza y blanqueamiento dental.',
      'Overnight monitoring for sleep disorders and apnea.': 'Monitoreo nocturno para trastornos del sueño y apnea.',

      // MembershipPlans
      'Tailored Care Plans': 'Planes de Atención Personalizados',
      'Choose a plan that fits your lifestyle and health needs. From basic monitoring to elite family protection.': 'Elija un plan que se adapte a su estilo de vida y necesidades de salud. Desde el monitoreo básico hasta la protección familiar de élite.',
      'Most Popular': 'Más Popular',
      'Basic Care': 'Atención Básica',
      'Premium Wellness': 'Bienestar Premium',
      'Elite Family': 'Familia Elite',
      'Essential health monitoring for everyone.': 'Monitoreo de salud esencial para todos.',
      'Comprehensive care for health-conscious individuals.': 'Atención integral para personas preocupadas por su salud.',
      'The ultimate healthcare protection for your whole family.': 'La máxima protección de salud para toda su familia.',
      'Monthly Health Report': 'Informe Mensual de Salud',
      'General Practitioner Chat': 'Chat con Médico General',
      'Standard Appointment Booking': 'Reserva de Citas Estándar',
      'Basic Medical Records': 'Registros Médicos Básicos',
      'Priority Appointment Booking': 'Reserva de Citas Prioritaria',
      'Specialist Consultations': 'Consultas Especializadas',
      'Detailed Wellness Analytics': 'Análisis Detallado de Bienestar',
      'Annual Full Body Scan': 'Escaneo Corporal Completo Anual',
      '24/7 Emergency Access': 'Acceso de Emergencia 24/7',
      'Unlimited Family Members': 'Miembros de la Familia Ilimitados',
      'Dedicated Family Physician': 'Médico de Familia Dedicado',
      'Home Visit Services': 'Servicios de Visita a Domicilio',
      'VIP Clinic Access': 'Acceso VIP a la Clínica',
      'Full Genomic Screening': 'Examen Genómico Completo',
      'Go Premium': 'Hacerse Premium',
      'Join Elite': 'Unirse a Elite',

      // FAQ
      'Quick answers to common questions about our world-class services.': 'Respuestas rápidas a preguntas comunes sobre nuestros servicios de clase mundial.',
      'How can I book an appointment?': '¿Cómo puedo reservar una cita?',
      'You can book an appointment through our online booking system via the \'Get Started\' button, or by calling our 24/7 helpline at +1 (555) 123-4567. We offer both virtual and in-person consultations.': 'Puede reservar una cita a través de nuestro sistema de reserva en línea mediante el botón \'Comenzar\', o llamando a nuestra línea de ayuda 24/7 al +1 (555) 123-4567. Ofrecemos consultas tanto virtuales como presenciales.',
      'Do you accept insurance?': '¿Aceptan seguros médicos?',
      'Yes, we accept most major health insurance providers. Please bring your insurance card during your first visit or upload a copy during the online registration process for faster verification.': 'Sí, aceptamos la mayoría de los principales proveedores de seguros médicos. Traiga su tarjeta de seguro durante su primera visita o suba una copia durante el proceso de registro en línea para una verificación más rápida.',
      'What should I bring for my first visit?': '¿Qué debo llevar para mi primera visita?',
      'Please bring a valid government-issued ID, your insurance card, and any previous medical records, test results, or current prescriptions you are taking to ensure a comprehensive evaluation.': 'Traiga una identificación válida emitida por el gobierno, su tarjeta de seguro y cualquier registro médico anterior, resultados de pruebas o recetas actuales que esté tomando para garantizar una evaluación integral.',
      'Is emergency care available?': '¿Hay atención de emergencia disponible?',
      'Absolutely. Our emergency department is open 24/7 with specialized trauma teams and advanced life-support equipment ready to assist you at any time.': 'Absolutamente. Nuestro departamento de emergencias está abierto las 24 horas, los 7 días de la semana, con equipos especializados en traumatología y equipos avanzados de soporte vital listos para ayudarlo en cualquier momento.',
      'Can I consult with a doctor online?': '¿Puedo consultar con un médico en línea?',
      'Yes, we provide a fully integrated telemedicine platform. You can have a high-definition video call with our specialists from anywhere in the world.': 'Sí, ofrecemos una plataforma de telemedicina totalmente integrada. Puede realizar una videollamada de alta definición con nuestros especialistas desde cualquier parte del mundo.',

      // CTA
      'Your Journey to Better Health Starts Here': 'Su viaje hacia una mejor salud comienza aquí',
      'Experience world-class healthcare tailored to your needs. Join Bashcare Hub today and get access to top specialists and seamless digital care.': 'Experimente una atención médica de clase mundial adaptada a sus necesidades. Únase a Bashcare Hub hoy mismo y acceda a los mejores especialistas y a una atención digital fluida.',
      'Consult a Specialist': 'Consultar a un especialista',

      // Footer
      'Providing excellence in medical care since 2024. We are committed to delivering the highest quality healthcare services to our community.': 'Brindando excelencia en la atención médica desde 2024. Estamos comprometidos a ofrecer servicios de salud de la más alta calidad a nuestra comunidad.',
      'Quick Links': 'Enlaces rápidos',
      'Specialties': 'Especialidades',
      'Help & FAQ': 'Ayuda y preguntas frecuentes',
      'Get Started': 'Comenzar',

      // About page additional
      'Leading the way in modern healthcare and patient management.': 'Liderando el camino en la atención médica moderna y la gestión de pacientes.',
      'Bashcare Hub was founded with a single goal: to make high-quality healthcare accessible, efficient, and compassionate. We bridge the gap between patients and providers through advanced technology and a dedicated network of medical professionals.': 'Bashcare Hub se fundó con un único objetivo: hacer que la atención médica de alta calidad sea accesible, eficiente y compasiva. Cerramos la brecha entre los pacientes y los proveedores a través de tecnología avanzada y una red dedicada de profesionales médicos.',
      'Our platform integrates everything from appointment booking and record management to doctor verification and hospital administration, ensuring a seamless experience for everyone in the healthcare ecosystem.': 'Nuestra plataforma integra todo, desde la reserva de citas y la gestión de registros hasta la verificación de médicos y la administración del hospital, garantizando una experiencia de usuario perfecta para todos en el ecosistema de la salud.',
      'Everything we do is focused on providing the best possible care for our patients.': 'Todo lo que hacemos se centra en proporcionar la mejor atención posible a nuestros pacientes.',
      'We strive for excellence in all our medical services and operational processes.': 'Nos esforzamos por alcanzar la excelencia en todos nuestros servicios médicos y procesos operativos.',
      'Leveraging the latest technology to improve healthcare accessibility and outcomes.': 'Aprovechando la última tecnología para mejorar la accesibilidad y los resultados de la atención médica.',
      'We maintain the highest standards of professional and ethical conduct.': 'Mantenemos los más altos estándares de conducta profesional y ética.',
      'A connected care experience for everyone': 'Una experiencia de atención conectada para todos',
      'From telehealth follow-ups to secure record sharing, Bashcare Hub brings patients, specialists, and hospitals together in one intelligent platform.': 'Desde el seguimiento de la telemedicina hasta el intercambio seguro de registros, Bashcare Hub reúne a pacientes, especialistas y hospitales en una sola plataforma inteligente.',
      'Virtual consultations': 'Consultas virtuales',
      'Book trusted specialists and talk to doctors online within minutes.': 'Reserve especialistas de confianza y hable con médicos en línea en minutos.',
      'AI-driven reminders': 'Recordatorios impulsados por IA',
      'Stay on top of care with intelligent health nudges and medication prompts.': 'Manténgase al tanto de la atención con alertas de salud inteligentes y recordatorios de medicamentos.',
      'Care coordination': 'Coordinación de la atención',
      'Link family, providers, and clinics for smoother treatment journeys.': 'Vincule a la familia, proveedores y clínicas para viajes de tratamiento más fluidos.',
      'Patients Served': 'Pacientes atendidos',
      'Hospital Partners': 'Hospitales asociados',
      'Support Available': 'Soporte disponible',

      // Contact page additional
      'Our Office': 'Nuestra oficina',
      'Phone Number': 'Número de teléfono',
      'Working Hours': 'Horas de trabajo',
      'Have questions about our platform or services? Reach out to us through any of the following channels. Our team is always ready to help.': '¿Tiene preguntas sobre nuestra plataforma o servicios? Comuníquese con nosotros a través de cualquiera de los siguientes canales. Nuestro equipo siempre está listo para ayudar.',
      'General Inquiry': 'Consulta general',
      'Technical Support': 'Soporte técnico',
      'Medical Partnership': 'Asociación médica',
      'Billing Question': 'Pregunta de facturación',
      'Fast Response': 'Respuesta rápida',
      'We answer support requests quickly so you can keep your health plans moving.': 'Respondemos rápidamente a las solicitudes de soporte para que pueda continuar con sus planes de salud.',
      'Verified Assistance': 'Asistencia verificada',
      'Our team is trained to handle medical coordination and patient portal issues.': 'Nuestro equipo está capacitado para manejar la coordinación médica y los problemas del portal del paciente.',
      'Secure Follow-Up': 'Seguimiento seguro',
      'All communication is handled with privacy and HIPAA-style care in mind.': 'Toda la comunicación se maneja teniendo en cuenta la privacidad y la atención al estilo HIPAA.',

      // Help page additional
      'Help & Support': 'Ayuda y Soporte',
      'Find answers to your questions or get in touch with our team.': 'Encuentre respuestas a sus preguntas o póngase en contacto con nuestro equipo.',
      'You can book an appointment by signing in as a Patient and navigating to the "Book Appointment" section. Choose your specialty, doctor, and preferred time slot.': 'Puede reservar una cita iniciando sesión como Paciente y navegando a la sección "Reservar Cita". Elija su especialidad, médico y horario de preferencia.',
      'Yes, we use industry-standard encryption and follow strict privacy protocols to ensure your health records are only accessible to you and your authorized healthcare providers.': 'Sí, utilizamos cifrado estándar de la industria y seguimos estrictos protocolos de privacidad para garantizar que sus registros médicos solo sean accesibles para usted y sus proveedores de atención médica autorizados.',
      'How can I verify my doctor credentials?': '¿Cómo puedo verificar las credenciales de mi médico?',
      'All doctors on our platform go through a rigorous verification process by our dedicated Verification Officers before they can offer consultations.': 'Todos los médicos en nuestra plataforma pasan por un riguroso proceso de verificación por parte de nuestros Oficiales de Verificación dedicados antes de poder ofrecer consultas.',
      'Can I manage multiple family members from one account?': '¿Puedo administrar a varios miembros de la familia desde una sola cuenta?',
      'Currently, each account is for an individual. However, we are working on a "Family Plan" feature to allow managed care for dependents.': 'Actualmente, cada cuenta es individual. Sin embargo, estamos trabajando en una función de "Plan Familiar" para permitir la atención administrada de los dependientes.',
      'What should I do in case of an emergency?': '¿Qué debo hacer en caso de una emergencia?',
      'Bashcare Hub is for non-emergency consultations. In case of a medical emergency, please call your local emergency services (e.g., 911) or go to the nearest hospital.': 'Bashcare Hub es para consultas que no son de emergencia. En caso de una emergencia médica, llame a los servicios de emergencia locales (por ejemplo, 911) o vaya al hospital más cercano.',
      'Need more help?': '¿Necesita más ayuda?',
      'Our support team is available 24/7 to assist you with any technical or medical inquiries.': 'Nuestro equipo de soporte está disponible las 24 horas, los 7 días de la semana, para ayudarlo con cualquier consulta técnica o médica.',
      'Live Chat': 'Chat en vivo',
      'Average response: 2 mins': 'Respuesta promedio: 2 min',
      'Email Us': 'Envíenos un correo electrónico',
      'Call Support': 'Llamar al soporte',
    },
    yo: {
      home: 'Ilé',
      services: 'Àwọn Ìsìn',
      about: 'Nípa Wa',
      contact: 'Kàn Sí Wa',
      help: 'Ìrànlọ́wọ́',
      dashboard: 'Ojú Aláfíà',
      appointments: 'Àwọn Ìpàdé',
      doctors: 'Àwọn Dókítà',
      messages: 'Àwọn Lẹ́tà',
      records: 'Àkọsílẹ̀ Ìṣègùn',
      prescriptions: 'Àkọsílẹ̀ Oògùn',
      notifications: 'Àwọn Ìdájọ́',
      settings: 'Àwọn Ìtòsílẹ̀',
      logout: 'Jáde',
      welcome: 'Kábọ̀',
      search: 'Wá',
      patients: 'Àwọn Alárìn',
      queue: 'Ilé Aláìsàn',
      consultations: 'Ìgbìmọ̀',
      schedule: 'Ìgbà',
      verifications: 'Àyẹ̀wò Kíkún',
      staff: 'Àwọn Òṣìṣẹ́',
      departments: 'Àwọn Ẹ̀ka',
      finance: 'Ìsówó & Ìṣúná',
      logs: 'Àkọsílẹ̀ Ètò',
      audit: 'Ìròyìn Àyẹ̀wò',
      directory: 'Atọ́ka Dókítà',
      pending: 'Àyẹ̀wò tó kù',
      overview: 'Ìwòye Kíkún',
      profile: 'Ojú-ewé Mi',
      users: 'Ìtọ́jú Olùdámọ̀ràn',
      monitoring: 'Ìṣọ́ Kíkún',
      vitals: 'Olùṣọ́ Ìlera',
      symptomGuide: 'Atọ́ka Àmì Aláìsàn',

      // Additional Yoruba
      'Now Accepting Online Consultations': 'A ti bẹ̀rẹ̀ sí gbà Ìpàdé lórí Íńtánẹ́ẹ̀tì nísinsìnyí',
      'Compassionate Care': 'Ìtọ́jú Pẹ̀lú Ìfẹ́',
      'for a Better Life': 'fún Ìgbésí Ayé Tó Dára Jù',
      'Bashcare Hub provides top-tier medical services with a team of experienced professionals. We are committed to your health and well-being.': 'Bashcare Hub ń pèsè àwọn iṣẹ́ ìlera tó ga jùlọ pẹ̀lú ẹgbẹ́ àwọn dókítà tó nímọ̀. A jẹ́ olóòótọ́ sí ìlera àti àlàáfíà rẹ.',
      'Search specialties, doctors, or symptoms...': 'Wá ẹ̀ka, dókítà, tàbí àmì àìsàn...',
      'Explore Services': 'Ṣàwárí Àwọn Ìsìn',
      'Our Specialists': 'Àwọn Amọ̀dájú Wa',
      'Active Doctors': 'Àwọn Dókítà tó ń ṣiṣẹ́',
      'Satisfaction Rate': 'Ìwọ̀n Ìtẹ́lọ́rùn',
      'Verified Staff': 'Òṣìṣẹ́ tí A Fọwọ́sí',
      'Top Rated Care': 'Ìtọ́jú Tó Ga Jùlọ',
      '98 Doctors Online': 'Dókítà 98 lórí Íńtánẹ́ẹ̀tì',
      'Cardiology': 'Ẹ̀ka Ọkàn',
      'Neurology': 'Ẹ̀ka Ọpọlọ',
      'Pediatrics': 'Ẹ̀ka Ọmọdé',
      'Orthopedics': 'Ẹ̀ka Egungun',
      'Dermatology': 'Ẹ̀ka Awọ-ara',
      'Book Appointment': 'Fi Àyè Sẹ́lẹ̀',
      'About Us': 'Nípa Wa',
      'Get Started': 'Bẹ̀rẹ̀ Nísinsìnyí',
      'Contact Us': 'Kàn Sí Wa',
      'Help & FAQ': 'Ìrànlọ́wọ́ & FAQ',
      'All rights reserved.': 'Gbogbo ẹ̀tọ́ wà ní pamọ́.',
      'Your Journey to Better Health Starts Here': 'Ìrìn-àjò rẹ sí Ìlera Tó Dára Jù Bẹ̀rẹ̀ Níhìn-ín',
      'Experience world-class healthcare tailored to your needs. Join Bashcare Hub today and get access to top specialists and seamless digital care.': 'Niriiri itọju ilera kilasi agbaye ti a ṣe deede si awọn aini rẹ. Darapọ mọ Bashcare Hub loni ki o ni iwọle si awọn amọja giga ati itọju oni-nọmba ti ko ni riran.',
      'Consult a Specialist': 'Sọ̀rọ̀ sí Amọ̀dájú',
      'Frequently Asked Questions': 'Àwọn Ìbéèrè tí A Ń Béèrè Jùlọ',
      'Quick answers to common questions about our world-class services.': 'Àwọn ìdáhùn kíákíá sí àwọn ìbéèrè tó wọ́pọ̀ nípa àwọn iṣẹ́ ìlera wa.',
      'Providing excellence in medical care since 2024. We are committed to delivering the highest quality healthcare services to our community.': 'Pípèsè ìtayọlọ́lá nínú ìtọ́jú ìṣègùn láti ọdún 2024. A jẹ́ olóòótọ́ sí pípèsè àwọn iṣẹ́ ìlera tó ga jùlọ sí àwùjọ wa.',
      'Quick Links': 'Àwọn Ìsopọ̀ Kíákíá',
      'Specialties': 'Àwọn Ẹ̀ka Amọ̀dájú',
    },
    de: {
      home: 'Startseite',
      services: 'Dienste',
      about: 'Über uns',
      contact: 'Kontakt',
      help: 'Hilfe',
      dashboard: 'Dashboard',
      appointments: 'Termine',
      doctors: 'Ärzte',
      messages: 'Nachrichten',
      records: 'Krankenakte',
      prescriptions: 'Rezepte',
      notifications: 'Benachrichtigungen',
      settings: 'Einstellungen',
      logout: 'Abmelden',
      welcome: 'Willkommen',
      search: 'Suche',
      patients: 'Meine Patienten',
      queue: 'Patienten-Warteschlange',
      consultations: 'Konsultationen',
      schedule: 'Dienstplan',
      verifications: 'Verifizierungsmonitor',
      staff: 'Personalverwaltung',
      departments: 'Abteilungen',
      finance: 'Abrechnung & Finanzen',
      logs: 'Systemprotokolle',
      audit: 'Prüfberichte',
      directory: 'Verifiziertes Verzeichnis',
      pending: 'Ausstehende Verifizierungen',
      overview: 'Übersicht',
      profile: 'Profil',
      users: 'Benutzerverwaltung',
      monitoring: 'Anforderungsüberwachung',
      vitals: 'Gesundheits-Tracker',
      symptomGuide: 'Symptom-Leitfaden',

      // Additional German
      'Now Accepting Online Consultations': 'Jetzt Online-Konsultationen akzeptieren',
      'Compassionate Care': 'Mitfühlende Pflege',
      'for a Better Life': 'für ein besseres Leben',
      'Bashcare Hub provides top-tier medical services with a team of experienced professionals. We are committed to your health and well-being.': 'Bashcare Hub bietet erstklassige medizinische Dienstleistungen mit einem Team erfahrener Fachkräfte. Wir setzen uns für Ihre Gesundheit und Ihr Wohlbefinden ein.',
      'Search specialties, doctors, or symptoms...': 'Suche nach Fachgebieten, Ärzten oder Symptomen...',
      'Explore Services': 'Dienste erkunden',
      'Our Specialists': 'Unsere Spezialisten',
      'Active Doctors': 'Aktive Ärzte',
      'Satisfaction Rate': 'Zufriedenheitsrate',
      'Verified Staff': 'Verifiziertes Personal',
      'Top Rated Care': 'Bestbewertete Pflege',
      '98 Doctors Online': '98 Ärzte online',
      'Cardiology': 'Kardiologie',
      'Neurology': 'Neurologie',
      'Pediatrics': 'Pädiatrie',
      'Orthopedics': 'Orthopädie',
      'Dermatology': 'Dermatologie',
      'Book Appointment': 'Termin buchen',
      'About Us': 'Über uns',
      'Get Started': 'Loslegen',
      'Contact Us': 'Kontaktieren Sie uns',
      'Help & FAQ': 'Hilfe & FAQ',
      'All rights reserved.': 'Alle Rechte vorbehalten.',
      'Your Journey to Better Health Starts Here': 'Ihre Reise zu besserer Gesundheit beginnt hier',
      'Experience world-class healthcare tailored to your needs. Join Bashcare Hub today and get access to top specialists and seamless digital care.': 'Erleben Sie eine erstklassige, auf Ihre Bedürfnisse zugeschnittene Gesundheitsversorgung. Treten Sie noch heute dem Bashcare Hub bei und erhalten Sie Zugang zu erstklassigen Spezialisten und nahtloser digitaler Pflege.',
      'Consult a Specialist': 'Spezialisten konsultieren',
      'Frequently Asked Questions': 'Häufig gestellte Fragen',
      'Quick answers to common questions about our world-class services.': 'Schnelle Antworten auf häufige Fragen zu unseren erstklassigen Dienstleistungen.',
      'Providing excellence in medical care since 2024. We are committed to delivering the highest quality healthcare services to our community.': 'Exzellente medizinische Versorgung seit 2024. Wir verpflichten uns, unserer Gemeinschaft Gesundheitsdienstleistungen von höchster Qualität zu bieten.',
      'Quick Links': 'Schnelllinks',
      'Specialties': 'Fachgebiete',
    },
    pt: {
      home: 'Início',
      services: 'Serviços',
      about: 'Sobre',
      contact: 'Contato',
      help: 'Ajuda',
      dashboard: 'Painel',
      appointments: 'Consultas',
      doctors: 'Médicos',
      messages: 'Mensagens',
      records: 'Registros Médicos',
      prescriptions: 'Receitas',
      notifications: 'Notificações',
      settings: 'Configurações',
      logout: 'Sair',
      welcome: 'Bem-vindo',
      search: 'Buscar',
      patients: 'Meus Pacientes',
      queue: 'Fila de Pacientes',
      consultations: 'Consultas',
      schedule: 'Agenda',
      verifications: 'Monitor de Verificação',
      staff: 'Gerenciamento de Equipe',
      departments: 'Departamentos',
      finance: 'Faturamento e Finanças',
      logs: 'Logs do Sistema',
      audit: 'Relatórios de Auditoria',
      directory: 'Diretório Verificado',
      pending: 'Verificações Pendentes',
      overview: 'Visão Geral',
      profile: 'Perfil',
      users: 'Gerenciamento de Usuários',
      monitoring: 'Monitoramento de Solicitações',
      vitals: 'Rastreador de Saúde',
      symptomGuide: 'Guia de Sintomas',

      // Additional Portuguese
      'Now Accepting Online Consultations': 'Aceitando Consultas Online Agora',
      'Compassionate Care': 'Cuidado Compassivo',
      'for a Better Life': 'para uma Vida Melhor',
      'Bashcare Hub provides top-tier medical services with a team of experienced professionals. We are committed to your health and well-being.': 'O Bashcare Hub oferece serviços médicos de alto nível com uma equipe de profissionais experientes. Temos o compromisso de cuidar da sua saúde e do seu bem-estar.',
      'Search specialties, doctors, or symptoms...': 'Buscar especialidades, médicos ou sintomas...',
      'Explore Services': 'Explorar Serviços',
      'Our Specialists': 'Nossos Especialistas',
      'Active Doctors': 'Médicos Ativos',
      'Satisfaction Rate': 'Taxa de Satisfação',
      'Verified Staff': 'Equipe Verificada',
      'Top Rated Care': 'Cuidado Altamente Avaliado',
      '98 Doctors Online': '98 Médicos Online',
      'Cardiology': 'Cardiologia',
      'Neurology': 'Neurologia',
      'Pediatrics': 'Pediatria',
      'Orthopedics': 'Ortopedia',
      'Dermatology': 'Dermatologia',
      'Book Appointment': 'Agendar Consulta',
      'About Us': 'Sobre Nós',
      'Get Started': 'Começar',
      'Contact Us': 'Contate-nos',
      'Help & FAQ': 'Ajuda & FAQ',
      'All rights reserved.': 'Todos os direitos reservados.',
      'Your Journey to Better Health Starts Here': 'Sua Jornada Para Uma Saúde Melhor Começa Aqui',
      'Experience world-class healthcare tailored to your needs. Join Bashcare Hub today and get access to top specialists and seamless digital care.': 'Experimente cuidados de saúde de classe mundial adaptados às suas necessidades. Junte-se ao Bashcare Hub hoje e tenha acesso aos melhores especialistas e cuidados digitais contínuos.',
      'Consult a Specialist': 'Consultar um Especialista',
      'Frequently Asked Questions': 'Perguntas Frequentes',
      'Quick answers to common questions about our world-class services.': 'Respostas rápidas para perguntas comuns sobre nossos serviços de classe mundial.',
      'Providing excellence in medical care since 2024. We are committed to delivering the highest quality healthcare services to our community.': 'Oferecendo excelência em cuidados médicos desde 2024. Estamos comprometidos em fornecer serviços de saúde da mais alta qualidade para nossa comunidade.',
      'Quick Links': 'Links Rápidos',
      'Specialties': 'Especialidades',
    }
  };

  useEffect(() => {
    document.documentElement.classList.toggle('dark', theme === 'dark');
    document.documentElement.setAttribute('data-theme', theme);
    localStorage.setItem('bashcare_theme', theme);
  }, [theme]);

  useEffect(() => {
    localStorage.setItem('bashcare_lang', language);
  }, [language]);

  const toggleTheme = () => setTheme(prev => prev === 'light' ? 'dark' : 'light');

  const t = (key) => translations[language][key] || key;

  return (
    <GlobalSettingsContext.Provider value={{ theme, toggleTheme, language, setLanguage, t }}>
      {children}
    </GlobalSettingsContext.Provider>
  );
};

export const useGlobalSettings = () => useContext(GlobalSettingsContext);
